### ISSUE TITLE
Unhide job

### ISSUE THREAD

**Issue by Wirl** [CGRU/cgru#129]
Hi,
What is the way to unhide a Job? Can not see how to, in afwatch or Web GUI.

Thanks for you help

**Comment by timurhai** [comment]
Hi.
In Afwatch there is a view options in top right corner of a nodes list. RMB on it, and there will be a menu for a hidden nodes.
WebGUI is already has such option (to show hidden nodes) but only in repo, will be available since the next release, or you can just update its javascripts for it.

ps
Such questions better to ask here
http://rules.cgru.info/#/Ask_Questions_Here/AFANASY
To let not only GitHub users to watch it.
GitHub on this project commonly users for developers.
