### ISSUE TITLE
Arnold render progress info in WebUI

### ISSUE THREAD

**Issue by eoyilmaz** [CGRU/cgru#146]
Hey Timur,

I have a problem with Arnold renders not showing any progress information in web ui.

I was playing with the code and as I understand we should have a generic ``maya`` parser, cause there is a ``maya`` service but there is no corresponding parser for that service that can parse arnold messages to extract the ``percentframe``.

So I've tried adding a ``maya.py`` file to cgru\afanasy\python\parsers. The code is fairly the copy of the ``arnold.py``, but it is not working:

```python
import re
# re.findall(r'(\|\s*)(\d*)(%\s*done)','12:34:56      32MB   |   45% done - 23 rays/pixel')
# |     0% done - 37 rays/pixel
re_percent = re.compile(r'(\s*)(\d*)(\s*% done)')


class maya(parser.parser):
	"""Generic maya parser
	"""

	def __init__(self):
		parser.parser.__init__(self)
		self.firstframe = True
		self.data_all = ''

	def do(self, data, mode):
		"""Missing DocString

		:param str data: Current portion of a task process output.
		:param str mode: One of the following:
			RUN: Task is running.
			EXIT_CODE:STOP_TIME :Task is not running: process exit status and
				stop time if task was asked to stop (zero if was not)
		:return:
		"""
		if len(data) < 1:
			return

		match = re_percent.findall(data)
		if len(match):
				percentframe = float(match[-1][1])
				self.percent = int(percentframe)
				self.percentframe = int(percentframe)

		self.calculate()
```

Do you have any suggestions?

**Comment by timurhai** [comment]
Hi.
How it is not working?

What is afrender process output?
And what is task process output?

**Comment by eoyilmaz** [comment]
I mean I don't see the individual frame progress as I see mentalRay renders. For example I can not see the frame is 25% rendered. It only shows 0% until the frame is finished, then shows 100%, that's all.

By the way I'm talking about mayabatch renders that using MtoA.

**Comment by timurhai** [comment]
You can double click task to see all its info. Ensure that it has parser you want. What submission script are you using?

**Comment by eoyilmaz** [comment]
I'm using the one inside ``cgru\cgru\plugins\maya\afanasy\__init__.py``

**Comment by timurhai** [comment]
I see, it only identifies mentalRay render

https://github.com/CGRU/cgru/blob/master/plugins/maya/afanasy/__init__.py#L249
And afjob.py set corresponding service.

Than maya_mental service describes its default parser:
https://github.com/CGRU/cgru/blob/master/afanasy/python/services/maya_mental.py#L4

"__init__.py" is a very ancient script. I stared it long ago, when Maya has no Python. It was written on MEL and constructs job giving command line arguments for afjob.py command (run python script as a command).
Now it is written on Python, and i even see that you is an author :)
It is much more simple, clean, flexible and comfortable to use Python API directly.
But as a quick solution you can just add to existing script check for maya_arnold just like for mental.

Any way we should add "maya_arnold.py" service and parser.

btw
Parser class can be inherited from other parser(s). You can look at the solution with Houdini. There is a "hbatch" parser to parser current frame (for several frames per task) and a "mantra" for per frame progress. This parses are used separately for hbatch and mantra (stand-alone) tasks. And there is a "hbatch_mantra" parser for houdini that runs mantra itself, this parser is inherited from both previous parsers and just runs them:
https://github.com/CGRU/cgru/blob/master/afanasy/python/parsers/hbatch_mantra.py#L23
( so there it does not parse anything itself )
Such approach is very useful, because if we use houdini with prman and has prman parser for stand-alone tasks, we can simple create hbatch_prman parser with a few lines of code:
https://github.com/CGRU/cgru/blob/master/afanasy/python/parsers/hbatch_prman.py#L23

**Comment by eoyilmaz** [comment]
Ok I've managed to add the ``maya_arnold`` service and parser and now I see the progress in WebUI, I'll create a patch for you to pull.
