### ISSUE TITLE
Afserver Error

### ISSUE THREAD

**Issue by IvonneBurgos** [CGRU/cgru#229]
Hello

So I started using version 2.1.0 maybe 2 days after release
Everything was fine but today keeper didnt start
I tried to started it from terminal but it send me a error
"Could not open socket" (sorry I didnt copy that error)
After a while, my last solution was to source ./setup.sh and then afserver
and this happened

```
master@master:/opt/cgru afserver
Compilation date = 'May  6 2016 00:54:37'
CGRU version = '2.1.0'
Afanasy build revision = '4c60391d6b14fb54ea98984133f234046c731fc0'
Python version = '2.7.6'
GCC version = '4.8.4'
RLIMIT_NOFILE: Files descriptors limit: 1024
RLIMIT_NPROC: Processes (threads) limit: 31349
Database connection "AFDB_update" is not working.
AFERROR: AFDB_upTables: Database connect failed: could not connect to server: Connection refused
	Is the server running on host "localhost" (127.0.0.1) and accepting
	TCP/IP connections on port 5432?

```
After a while it worked but I dont want to source each time I want to use afanasy. I was fine until friday, last day I worked with it.

SORRY FOR THE OTHER 2 MESSAGES. WHEN I SEND THE ISSUE IT DIDNT APPEAR.

**Comment by eliemichel** [comment]
_(GitHub seemed to have weird behavior during last hours, I think that's why you did not see your issues at first. But please, avoid using all caps messages since it looks aggressive!)_

What is your answer to this question that the error message asked you?

    Is the server running on host "localhost" (127.0.0.1) and accepting TCP/IP connections on port 5432?

**Comment by IvonneBurgos** [comment]
Sorry I was having trouble posting this thats why I write with caps last phrase and title. 

I really don't know the problem. I worked with afanasy in my house and office. But office afanasy failed today. I searched about that error and they said it was a problem with postgresql but I'm not using postgresql. 

Maybe is there a method to delete all files created by afanasy and start a clean installation?. 

thanks

**Comment by IvonneBurgos** [comment]
This was the error when I wanted to start keeper form terminal
```
CGRU_VERSION 2.1.0 : '/opt/cgru'
master@master:/opt/cgru$ ./start.sh
PySide module imported.
Could not open socket.
127.0.0.1 : [Errno 111] Connection refused
Listening 50999 port...
Could not open socket.
127.0.0.1 : [Errno 111] Connection refused
```
Then I source and afrender and it start working but I didnt have to do that before.

**Comment by predat** [comment]
Hello @IvonneBurgos,

Apparently you are using a unix os, so when you have install cgru, afserver was start automatically during installation. A 'render' user was created during installation and cgru use this user to start afserver.
Messages related to database connection are not really a problem because postgresql is only use for logging statictics and afserver does not matter if database does not exists. It's only warning messages.

Sourcing setup.sh is a necessity because cgru binaries (afserver, afrender, afwatch ...etc) are using environnement variables when starting (like cgru root directory...).

When afserver is start using os services, it using /opt/cgru/afanasy/init/afserver to set all of those environnement variables for you.

You problem is not really a development issue and it's better to ask thoses questions on http://rules.cgru.info/#/Ask_Questions_Here.

**Comment by IvonneBurgos** [comment]
Thanks! 
I'm using Ubuntu 14.04 and sorry it was not afrender it was afserver after sourcing. Now you said about environment variables I set cgru variables directly on environment file so I deleted them and it works again.

**Comment by predat** [comment]
I do not understand all about your last comment. Cgru installation do all the environnement variable tasks for you but if it's ok for you, i can close the issue. Right ?

**Comment by IvonneBurgos** [comment]
Yeah I was trying something that went wrong but thanks to you I fixed it.
Thanks
