### ISSUE TITLE
af_render doesn't seem to run a process under the user who submitted the job!

### ISSUE THREAD

**Issue by hradec** [CGRU/cgru#251]
Am I right in conclud that af_render doesnt run a process under the user who submitted the job? 

for example, in out setup, we have installed af_render as root in all linux machines, but it seems when a job runs, it runs under root, not the original user who submitted the job! 

for now, we managed to get around by submitting the cmd line enclosed in a "su -l <user> -c <cmd>" so the process runs under the username, but we're seeing some weird random behaviour were a process complains about not having permission to write in a user folder, or failling to load data because of access rights.

**Comment by timurhai** [comment]
Yes, afrender does not changes user for child processes.

**Comment by eliemichel** [comment]
I would add that in my opinion this is a feature, not a bug. ;)

It lets you the freedom of `su`-ing, or not. In some setups, you might want to run `afrender` with a low privileged user, that could not `su` to other users, etc. Using `su` is the way to go.

The random behavior you report must be due to some issue on your setup.

That being said a "Run as user XXX" feature in job/block/task parameters could be handy. An issue suggesting this improvement could be opened.

**Comment by timurhai** [comment]
Note that you can change command in a Python service class. You can prefix command with su-ing. Service class has all info about a task, you can get username there.
