### ISSUE TITLE
Block.setDependMask doesn't seems to wait for the block to finish

### ISSUE THREAD

**Issue by hradec** [CGRU/cgru#256]
I'm trying to setup a job with 2 blocks. 

First block has 10 tasks (rendering a huge image in tiles). 
Second block has one task to "stitch" the tiles into an image. 

I've tried the following to setup dependency between the blocks:
```
block2.setDependMask( block1_name )

block2 does not wait and starts right away a task starts on block1
```

```
block2.setDependMask( self.name )
block2.setDependSubTask() 

this time, block2 task was started after all tasks in block one 
had started, but it didn't wait any of then to finish! 
```

I've also notice that Block has a setTasksDependMask()  method. I've tried that too, passing the name of the previous block, the name of the tasks (separated by coma) in the previous block and the name of the LAST TASK, in the previous block, but still the task starts before the previous block has being finished! 

make sense? 

What is the proper setup for a block2 (and all tasks in it) to wait until all the tasks in block1 are finished?

**Comment by lithorus** [comment]
The example you gave should work.

Could you provide more details about versions etc.? Also perhaps a complete
example.

- Jimmy
On 29 Jun 2016 20:44, "Hradec" <notifications@github.com> wrote:

I'm trying to setup a job with 2 blocks.

First block has 10 tasks (rendering a huge image in tiles).
Second block has one task to "stitch" the tiles into an image.

I've tried the following to setup dependency between the blocks:

block2.setDependMask( block1_name )
block2 does not wait and starts right away a task starts on block1

block2.setDependMask( self.name )
block2.setDependSubTask()

this time, block2 task was started after all tasks in block one had
started, but it didn't wait any of then to finish!

I've also notice that Block has a setTasksDependMask() method. I've tried
that too, passing the name of the previous block, the name of the tasks
(separated by coma) in the previous block and the name of the LAST TASK, in
the previous block, but still the task starts before the previous block has
being finished!

make sense?

So, how can I set a block2 (and all tasks in it) to wait until all the
tasks in block1 are finished?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/CGRU/cgru/issues/256>, or mute the thread
<https://github.com/notifications/unsubscribe/ABUio1KeC1w1pbTwk4IrCPPPAgvI6yW7ks5qQrz7gaJpZM4JBcUt>
.
