### ISSUE TITLE
RegEx library differences

### ISSUE THREAD

**Issue by sebastianelsner** [CGRU/cgru#267]
I just noticed that the GUI and the server are using different regex libraries. The GUI is using QRegExp and the server (on Linux) the systems regex library. At least on Linux they use incomatible syntax.

for example "workstation\d.*" will match in the gui (perl-like regex), but not as the host mask of a job, because POSIX regex does not support "\d". 
Also the included regex testing gui in "utilities/regex" folder only uses the QtCore's Regex.
This is confusing and the webpage also talks about afanasy's regex being pearl like. In the long run this should be fixed.

What this means for the user: you cannot test a regex in the gui (for example in the renders filter) and then be sure the regex works on the server side.

**Comment by timurhai** [comment]
Hi.
Yes, sure, afwatch and afserver should (and can) use the same library.
This should be fixed.
But how to use the same from PyQt and WebGUI?

**Comment by sebastianelsner** [comment]
It does not need to be the same, it just needs to be mostly the same compatibility wise: POSIX or perl.
server/render (linux) : POSIX/native library
watch: Qt/perl-like
WebUI: javascript/perl-like
PyQt: Qt/perl-like

so the most sane option would be to bundle a regex lib for the server/render

**Comment by timurhai** [comment]
Hi.
So now we have the same library for afwatch and afserver.
All regex is incapculated in af::RegExp class.
And it is POSIX for now for Linux.
Note that for windows it was always PERL:
https://github.com/CGRU/cgru/blob/master/afanasy/src/libafanasy/regexp.h#L52
And class is ready to use std::regex that is ECMAScript by defaul (perl-like).
But it is c++11 standart, that gcc started to support since 4.9.
So on my work with ubuntu14 (gcc4.8) it does not work.
But on my notebook ubuntu16 (gcc5.4) it works.

 - We can detect gcc version in code to use POSIX/std::regex, and soon it will be perl on everywhere.
 - We can use boost on linux (may be just if gcc < 4.9).

Or, any ideas?

**Comment by sebastianelsner** [comment]
I think its ok as of now, since it is consistent.
