### ISSUE TITLE
Block (tasks) environment parameter.

### ISSUE THREAD

**Issue by timurhai** [CGRU/cgru#295]
It will be useful for tasks along with a working directory, have some extra environment for a child process.
This can be a sting map with a string key, value pairs (`std::map<std::string, std::string>`) that should be added to a parent process environment.

Note, that when Afanasy project started there was a `std::string` environment parameter:
https://github.com/CGRU/cgru/blob/996f291d0ab2d4c45d076f1a57e9aafdfde8693e/afanasy/src/libafanasy/taskexec.h#L158
that was designed to keep `key1=value1;key2=value2` but it was not used, i just decided to complete it when it became needed at work.
-and after 8 years of the project it became needed :)
   ( to keep such variables as scene, shot, version and so on )

Also environment can be used to pass some data between tasks.
For example, this can be used to solve such things as Houdini distribute simulations tracker.
Tracker can be launched in one task, and this task can add tracker address and port to other job block via environment.

**Comment by timurhai** [comment]
Done for Linux.
The next is the same for windows and testing.

**Comment by lithorus** [comment]
I can already see myself using the feature the moment 2.2.0 is out :)

A few things though :

It would be nice to have a way of either appending or overriding an environment variable. Eg. either key1=value1;key2+=value1

(and perhaps another seperator character than ; since it's already a path seperator in Windows, perhaps | instead?)

Also it would be nice to also have it used when launching applications on the task outputs in afwatch.

**Comment by timurhai** [comment]
Hi.
It is a pairs `std::map<std::string, std::string>` now. No separators needed.
For afwatch - yes, it will be easy to implement, as it receives all `af::Taskexec` data with extra environment too.
