### ISSUE TITLE
afcmd tout: No monitor with ID = ...

### ISSUE THREAD

**Issue by sergiy-nazarenko** [CGRU/cgru#303]
Hello! 
I want to see the progress of some task through afcmd I got a following output:

> afcmd tout 4 0 4 0
Task['TOutput']: Pos: TP: j4 b0 t4
Progress: s2 p53% (0-53%)s6/6e (12:38.40-12:38.47=01:00.07) - aftester
JobName = 'sc99_sh001__fx_test', << BlockName = 'dust', TaskName = 'frame 21-25'
Service = 'mantra', Parser  = 'mantra'
MonitorContainer::waitOutput: No monitor with ID = 0
>

It happens each time when some task still in proggress. If task is done the output is as expected.
Is it normal behavior of afcmd right now or it will be fixed?

Thanks,
Sergiy

**Comment by timurhai** [comment]
Hi!
There is now way for `afcmd` to get running task output, since afrender does not listens any port.
I should check server code, what happens if there is monitor ID in this message:
https://github.com/CGRU/cgru/blob/master/afanasy/src/cmd/cmd_task.cpp#L62
I'll make server to answer some info about this issue.

ps
Since clients are listen no port, getting running task output became much more complex and based on render and monitor internal events.

**Comment by timurhai** [comment]
wow, do not hurry ))
i'll reopen it, to not to forget to make a small fix (change message that afcmd will receive)

**Comment by timurhai** [comment]
I also want to notice you, that since afanasy got json protocol, afcmd simple constructs a sting with a json request:
https://github.com/CGRU/cgru/blob/master/afanasy/src/cmd/cmd_task.cpp#L63
You can use json protocol directly to not to parse afcmd output.
