### ISSUE TITLE
Multi-licensing.

### ISSUE THREAD

**Issue by timurhai** [CGRU/cgru#311]
Example situation:
We have some soft with 20 licenses and some plugin for it with 5 licenses.
We can call services as `soft` and `soft_plus`.
For now it will be 2 different services with no influence on each other.
And there is no way to count this licenses proper.
(`soft_plus` launch will not increment `soft`)

But if server will understand that `soft_plus` is a sub-service of a `soft`.
It can increment `soft` license on each `soft_plus` launch.
And it can block `soft_plus` launch if there is already no one `soft` license.

**Comment by lithorus** [comment]
Not sure I like that approach as some plugins are multihost, like for
instance vray and yeti render licences.

**Comment by sebastianelsner** [comment]
what do you mean with multihost? they are plugins with one license per host, too? Or not?

**Comment by lithorus** [comment]
For instance :

Vray for Maya :
  - maya (doesn't really take a license)
  - vray render license

Vray for Max :
  - max (doesn't really take a license)
  - vray render license

Vray for Nuke:
  - nuke render license
  - vray render license

They all use the same type vray render license.

So in this case it's better to specify both services since the vray render
license pool is shared with all softwares.

**Comment by timurhai** [comment]
I see.
So it will be useful for task to have several services?
Hm.
May be better to add some more parameter - `licenses`, for example.
And it can be an array of strings.
By default it will be `licenses = [service]`.
What do you think?

**Comment by luizgarrido** [comment]
Let me try to help.
The problem was found with Nuke and Revision plugin. We have 28 nuke licenses and 10 revision licenses. But for each Revision job, I need to use a Nuke license too.

The way that is now, the service will consume all 10 revision licenses but I still have 28 nuke licenses instead of 18. We need to subtract from the nuke service too when using this specific plugin for example. So, when we launch a job that requires a revision license, it need to consume a nuke license too.

**Comment by mlesin** [comment]
May be it would be better to allow specify multiple services at once, without any subdependencies. Like tags. This way you can count licenses, and it would be much easier to separate things like hbatch, mantra and hbatch_mantra (the latter wouldn't needed anymore, it will be enough to tag is as both hbatch and mantra services)

**Comment by lithorus** [comment]
Multiple services can also be used for special setups for different plugins
at render time especially if it's extended with version information.

The license count can be done with limits > maxhosts (ot maxcount depending
on the licensing scheme)

- Jimmy

**Comment by sebastianelsner** [comment]
yea, the multi-service approach would be more felixible it seems.

**Comment by timurhai** [comment]
Ok)

So, services will be the same.
Block (task) will have only one service.
There will be a new object: license.
Service will describe default parser and default licenses array.
Block (task) will have a new attribute - licenses (std::vector<std::string>).
Afsever should count licenses (instead of services).

Ok?

**Comment by mlesin** [comment]
I think it will be more limited than multiple services, and will grow essences without any need to.
Licenses are not only reason to have them, the other one is to set limits on resources, which are defined on hosts. There is already lots of services combining each other: hbatch_mantra, houdinitoarnold, and so on. Lets get rid of them instead of making another essence!

**Comment by lithorus** [comment]
I'm actually for getting multiple a 'license' attribute. I first also thought about getting rid of services, but it makes sense to use as a way to specifiy what software is installed. But perhaps there should be more focus on distinguish parser from service.
Eg. hbatch_mantra and houdinitoarnold could both be using the same service but have different parsers. Changing the service attribute to a string array would also break the API considerably, where as what @timurhai described should not break any existing scripts.

**Comment by timurhai** [comment]
I will definitely return to this issue, but later. Busy with other things for now.
( and it will not be in 2.2.1 )

**Comment by sssk2006** [comment]
Hi all! 
We have recently hit this same requirement about having AF to keep track of multiple service licenses for the same task ( our case mostly is Arnold + Yeti or Redshift + Yeti ) 
Was wondering if someone managed to figure out a way around this ? 
Any kind of input would be very helpful. Thanks in advance!

**Comment by timurhai** [comment]
Hi.
For now i finished Branches (http://cgru.info/afanasy/branch). Soon there will be a new release (with Branches).
Later we will have 2 needed features in the roadmap: render pools and something with licenses counting.
For now i can't say when licensing will be implemented, may be in a year or two, i do not know. But i can say that it is a useful and needed feature and it will be implemented.

**Comment by sssk2006** [comment]
Thanks for the reply @timurhai . Good to know!

**Comment by timurhai** [comment]
Tickets appeared in the 3 version, that we started to use in a real production.
https://github.com/CGRU/cgru/issues/459
Multi-licensing can be solved via tickets.
