### ISSUE TITLE
CentOS tmpwatch

### ISSUE THREAD

**Issue by sebastianelsner** [CGRU/cgru#365]
I just found out, that there is a default daily cron job on CentOS 6 (maybe 7 as well), that is looking at /var/tmp/ (which is the afanasy default store) and deleting files older than 30 days (in some cases 10 days). It seems to be a bad idea to have afanasy's json files there. Is this the same on Debian?

**Comment by timurhai** [comment]
Hi.
No, i did not noticed that debian-like distros clearing this folder periodically.
You can change it here:
https://github.com/CGRU/cgru/blob/master/afanasy/config_default.json#L28

**Comment by lithorus** [comment]
I would argue that /var/lib/afanasy would be a better default place. Didn't afanasy used to be depending on an external database for job info and the "tmp" directory is for legacy reasons?


_Sent from my LGE LG-H815 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by timurhai** [comment]
At first, afanasy stored all jobs, users and renders data in SQL database.
TMP folder was used only for tasks outputs.
Since 2.x afanasy stores data in json files in TMP folder.
( It can use SQL, but for statistics only )
/var/tmp/afanasy was chosen as it is writable to all

But i agree, since afanasy starts to store all in json files, name "temporary" folder became less suitable for it. It is a "store" folder now. And may be can be placed in a more suitable location. But we should take care about its writable status in this case. On server start we should say that it is not writable and exit (like some soft does).

**Comment by lithorus** [comment]
How about this?
Move afserver json files into /var/lib/afanasy and log files for both afserver and afrender into /var/log/?

There are installer scripts which takes care of creating the "render" user if it's not already there which could also take care of the permissions and such.

**Comment by lithorus** [comment]
Actually come to think of it afrender log files might be better to have in a directory which is writable by anyone as it can be run as any user.

**Comment by cg-cnu** [comment]
Just tested out on cento7 there is no cron job clearing up /var/tmp/

**Comment by cg-cnu** [comment]
@sebastianelsner Stil I would like to keep that as an enhancement.

**Comment by timurhai** [comment]
Hi.
What we should enhace?
Just change default store folder?
