### ISSUE TITLE
subtask dependencies seem to wait at the last frame of unbroken sequence

### ISSUE THREAD

**Issue by ultra-sonic** [CGRU/cgru#508]
Hi Timur,
long time no see...hope you are doing well!

Here is my story in short:
render-block has 100 tasks from 1001-1100 - 99 tasks are finished except frame 1050
post-render-block (which is task-depending on render-block) only started tasks 1001-1049 so far but it could have started 1051-1100 already.

This is kind of big deal especially for time critical jobs. In my opinion also easy to fix?
Can you point me to the part of the code that cause this issue?

Thanks in advance
Oliver

**Comment by timurhai** [comment]
Hi Oliver!

This issue is connected with this one:
https://github.com/CGRU/cgru/issues/6

Now Afsever tries to solve the first block ready task, with a recursion on dependencies.
It is not good generally. It can take a long time to try solve all ready tasks.

I have plans to rewrite it. Add a new task state: WAIT_DEPENDS [WD]. Chech dependecies once in a special function.
Then Afanasy server can try to solve all ready tasks (not one) w/o any recursion and it will be fast. As WD tasks will ne not RDY.

That recursion mechanism was not a good choise on a program architecture develop, sorry.

**Comment by ultra-sonic** [comment]
understood! thanks for the fast reply! i'll wait for the re-write then :)
this also explains why some of our jobs with lots of blocks and tasks are giving afserver a hard time :wink:

**Comment by timurhai** [comment]
Done. Now on testing:
https://github.com/CGRU/cgru/issues/6

**Comment by ultra-sonic** [comment]
thanks a lot Timur! you're the best!
